In [1]:
# mount google drive 
from google.colab import drive
ROOT = '/content/drive'
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import os
import sys
from os.path import join 
repo_dir = '/content/drive/MyDrive/metaphor-detection'

In [3]:
## directories for resources
data_dir = repo_dir + '/resources/metaphor-in-context/data/'
glove_dir = repo_dir + '/resources/glove/'
elmo_dir = repo_dir + '/resources/elmo/'


In [4]:
# installing the requirements
%cd 'drive/MyDrive/metaphor-detection/' 
#;!pip install allennlp
#!pip install -r gao-g-requirements.txt
#!pip install --upgrade google-cloud-storage

/content/drive/MyDrive/metaphor-detection


In [5]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable
from torch.utils.data import DataLoader

from core.gao_files.classification.model import RNNSequenceClassifier
import time
import matplotlib
from core.gao_files.classification.util import *
from core.data.gao_data import *
import h5py
import math
import numpy as np

## Data Preperation

In [6]:
### Read MOH-x Data 
data_dir = os.path.join("resources", "metaphor-in-context", "data")
data_container = ExperimentData(data_dir)
data_container.read_moh_x_data(to_pandas = False)
moh_x_data = data_container.moh_x_formatted_svo_cleaned


MOH-X formatted svo nrow: 647
MOH-X formatted svo cleaned nrow: 647


In [7]:
### Pre-Process Data
vocab = get_vocab(moh_x_data)
word2idx, idx2word = get_word2idx_idx2word(vocab)
glove_embeddings = get_embedding_matrix(glove_dir + 'glove840B300d.txt', 
                                        word2idx, 
                                        idx2word, 
                                        normalization=False)

vocab size:  453


100%|██████████| 2196017/2196017 [00:48<00:00, 44819.28it/s]

Number of pre-trained word vectors loaded:  453
Embeddings mean:  -0.0009290720336139202
Embeddings stdev:  0.38682886958122253


In [8]:
NUM_SUFFIX_TAG = 2
elmo_embeddings = h5py.File(elmo_dir + 'MOH-X_cleaned.hdf5', 'r')
suffix_embeddings = nn.Embedding(NUM_SUFFIX_TAG, 50)

In [9]:
## Embedding Datasets
embedded_data = [[embed_sequence(data[3].strip(), int(data[4]), word2idx, glove_embeddings, elmo_embeddings, suffix_embeddings), int(data[-1])] for data in moh_x_data]
sentences = [data[0] for data in embedded_data]
labels = [data[1] for data in embedded_data]

## K-Fold Training

In [10]:
print(f"Data Length is {len(moh_x_data)}")
NUMBER_FOLD = 10
fold_size = round(len(moh_x_data) / NUMBER_FOLD)
print(f"Each fold size is {fold_size}")

Data Length is 647
Each fold size is 65


In [11]:
folds = []
for i in range(NUMBER_FOLD):
    folds.append((sentences[i * fold_size:(i + 1) * fold_size], labels[i * fold_size: (i + 1) * fold_size]))


In [27]:
optimal_f1s = []
accuracies = []
precisions = []
recalls = []
BATCH_SIZE = 10
using_GPU = True
NUM_EPOCHS = 30
for i in range(NUMBER_FOLD):
    ### DATA BATCHING
    training_sentences = []
    training_labels = []
    for j in range(NUMBER_FOLD):
        if j != i:
            training_sentences.extend(folds[j][0])
            training_labels.extend(folds[j][1])
    training_dataset_mohX = TextDatasetWithGloveElmoSuffix(training_sentences, 
                                                           training_labels)
    val_dataset_mohX = TextDatasetWithGloveElmoSuffix(folds[i][0], 
                                                      folds[i][1])

    # Data-related hyperparameters
    # Set up a DataLoader for the training, validation, and test dataset
    train_dataloader_mohX = DataLoader(dataset=training_dataset_mohX, 
                                       batch_size=BATCH_SIZE, 
                                       shuffle=True,
                                      collate_fn=TextDatasetWithGloveElmoSuffix
                                                .collate_fn)
    val_dataloader_mohX = DataLoader(dataset=val_dataset_mohX, 
                                     batch_size=BATCH_SIZE, 
                                     shuffle=True,
                                      collate_fn=TextDatasetWithGloveElmoSuffix
                                                .collate_fn)
    rnn_clf = RNNSequenceClassifier(num_classes=2, 
                                    embedding_dim=300+1024+50, 
                                    hidden_size=300, num_layers=1, 
                                    bidir=True,
                                    dropout1=0.2, dropout2=0, dropout3=0.2)
    nll_criterion = nn.NLLLoss()
    if using_GPU:
        rnn_clf = rnn_clf.cuda()
        nll_criterion = nll_criterion.cuda()

    rnn_clf_optimizer = optim.SGD(rnn_clf.parameters(), lr=0.02, momentum=0.9)
    #### TRAIN ####
    training_loss = []
    val_loss = []
    val_p = []
    val_r = []
    val_acc = []
    training_f1 = []
    val_f1 = []
    num_iter = 0
    train_dataloader = train_dataloader_mohX
    val_dataloader = val_dataloader_mohX
    for epoch in range(NUM_EPOCHS):
        print("-----Starting epoch {}------".format(epoch + 1))
        now = time.time()
        for (example_text, example_lengths, labels) in train_dataloader:
            example_text = Variable(example_text)
            example_lengths = Variable(example_lengths)
            labels = Variable(labels)
            if using_GPU:
                example_text = example_text.cuda()
                example_lengths = example_lengths.cuda()
                labels = labels.cuda()

            # predicted shape: (batch_size, 2)
            predicted = rnn_clf(example_text, example_lengths)
            batch_loss = nll_criterion(predicted, labels)
            rnn_clf_optimizer.zero_grad()
            batch_loss.backward()
            rnn_clf_optimizer.step()
            num_iter += 1
            # Calculate validation and training set loss and accuracy every 200 gradient updates
            if num_iter % 200 == 0:
                passed = now - time.time()
                now = time.time()
                avg_eval_loss, eval_accuracy, precision, r, f1, val_fus_f1 = evaluate(val_dataloader, rnn_clf, nll_criterion, using_GPU)
                val_loss.append(avg_eval_loss)
                val_acc.append(eval_accuracy.item())
                val_f1.append(f1)
                val_r.append(r)
                val_p.append(precision)
                print(
                    """####################Iteration {}.#############
                       Validation Loss {}. Validation Accuracy {}. 
                       Validation Precision {}. Validation Recall {}. 
                       Validation F1 {}. Validation class-wise F1 {}. 
                       Time passed {}###############################""".format(
                        num_iter, avg_eval_loss, eval_accuracy, val_p, val_r, val_f1, val_fus_f1, passed))
                # filename = '../models/LSTMSuffixElmoAtt_???_all_iter_' + str(num_iter) + '.pt'
                # torch.save(rnn_clf, filename)
                avg_eval_loss, eval_accuracy, precision, recall, f1, fus_f1 = evaluate(train_dataloader, rnn_clf, nll_criterion, using_GPU)
                training_loss.append(avg_eval_loss)
                training_f1.append(f1)
                #accuracies.append(eval_accuracy.item())
                #if str(precision) != "nan":
                #precisions.append(precision)
                #recalls.append(recall)
                #if str(max(val_f1)) != "nan":
                training_loss.append(avg_eval_loss)
                training_f1.append(f1)
                print(
                    """######################Iteration {}######################. 
                      Training Loss {}. Training Accuracy {}. Training Precision {}. 
                      Training Recall {}. Training F1 {}. Training class-wise F1 {}.""".format(
                        num_iter, avg_eval_loss, eval_accuracy, precision, recall, f1, fus_f1))
                
            
    print("Training done for fold {}".format(i))
    optimal_f1s.append(max(val_f1))
    #if str(max(val_f1)) != "nan":
    print('val_f1: ', val_f1)
    idx = 0
    if math.isnan(max(val_f1)):
        optimal_f1s.append(max(val_f1[6:]))
        idx = val_f1.index(optimal_f1s[-1])
        precisions.append(val_p[idx])
        recalls.append(val_r[idx])
        accuracies.append(val_acc[idx])
    else:
        optimal_f1s.append(max(val_f1))
        idx = val_f1.index(optimal_f1s[-1])
        precisions.append(val_p[idx])
        recalls.append(val_r[idx])
        accuracies.append(val_acc[idx])
            

print('F1 on MOH-X by 10-fold = ', optimal_f1s)
print('F1 on MOH-X = ', np.mean(np.array(optimal_f1s)))
print('precisions on MOH-X = ', np.mean(np.array(precisions)))
print('recalls on MOH-X = ', np.mean(np.array(recalls)))
print('accuracies on MOH-X = ', np.mean(np.array(accuracies)))


-----Starting epoch 1------
-----Starting epoch 2------
-----Starting epoch 3------
-----Starting epoch 4------
[[ 6.  2.]
 [27. 30.]]
####################Iteration 200.#############
                       Validation Loss 1.0874603597017436. Validation Accuracy 55.38461685180664. 
                       Validation Precision [52.63157894736842]. Validation Recall [93.75]. 
                       Validation F1 [67.41573033707866]. Validation class-wise F1 48.34201151000274. 
                       Time passed -0.13670587539672852###############################


/content/drive/MyDrive/metaphor-detection/core/gao_files/classification/util.py:178: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  eval_text = Variable(eval_text, volatile=True)
/content/drive/MyDrive/metaphor-detection/core/gao_files/classification/util.py:179: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  eval_lengths = Variable(eval_lengths, volatile=True)
/content/drive/MyDrive/metaphor-detection/core/gao_files/classification/util.py:180: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  eval_labels = Variable(eval_labels, volatile=True)


[[150.  12.]
 [149. 271.]]
######################Iteration 200######################. 
                      Training Loss 0.5287285624039951. Training Accuracy 72.3367691040039. Training Precision 64.52380952380952. 
                      Training Recall 95.75971731448763. Training F1 77.09815078236132. Training class-wise F1 71.08703634562752.
-----Starting epoch 5------
-----Starting epoch 6------
-----Starting epoch 7------
[[15.  6.]
 [18. 26.]]
####################Iteration 400.#############
                       Validation Loss 0.8601410113848172. Validation Accuracy 63.07692337036133. 
                       Validation Precision [52.63157894736842, 59.09090909090909]. Validation Recall [93.75, 81.25]. 
                       Validation F1 [67.41573033707866, 68.42105263157895]. Validation class-wise F1 61.98830409356725. 
                       Time passed -0.25832414627075195###############################
[[275.   9.]
 [ 24. 274.]]
######################Iteration 400########

In [28]:
gao_results = [75.3, 84.3, 79.1, 78.5]
our_results = [round(np.mean(np.array(precisions)), 2),
               round(np.mean(np.array(recalls)), 2),
               round(np.mean(np.array(optimal_f1s)), 2),
               round(np.mean(np.array(accuracies)), 2)]

In [34]:
results = pd.DataFrame([gao_results, our_results], 
                       columns = ['P', "R", "F1", "Acc"],
                       index = ["GAO", "US"])

In [36]:
results

P      R     F1    Acc
GAO  75.30  84.30  79.10  78.50
US   74.12  78.29  75.79  75.57